version: '3.4'
services:
  shopping_cart:
    restart: always
    image: shopping-cart:latest
    network_mode: host
    ports:
      - "8080:8080"
    environment:
      - DEBUG=false
      - SC_ACCESS_TOKEN_SECRET_KEY=5h0pp1ng_k4rt
      - SC_JWT_SECRET_KEY=-*5h0pp1ng_k4rt*-
      - SC_JWT_CLAIM={"claim": "004b4457-71c3-4439-a1b2-03820263b59c"}
      - SC_ADMIN_USER_TOKEN=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJjbGFpbSI6ICIwMDRiNDQ1Ny03MWMzLTQ0MzktYTFiMi0wMzgyMDI2M2I1OWMifQ.8PYToq2D4q4DaE06gG8paYt4AvvJir2f6rgsI2GflQw
      - SC_PASSWORD_SALT=06!grsnxXG0d*Pj496p6fuA*o
      - SC_APP_ENV=test
